
¾root"_tf_keras_model*ž{"name": "gcn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "GCN", "config": {"n_labels": 2, "channels": 16, "activation": "relu", "output_activation": "softmax", "use_bias": false, "dropout_rate": 0.5, "l2_reg": 0.00025, "n_input_channels": 39522}, "shared_object_id": 0, "is_graph_network": false, "full_save_spec": {"class_name": "__tuple__", "items": [[{"class_name": "__tuple__", "items": [{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [5002, 39522]}, "float32", "input_1"]}, {"class_name": "TypeSpec", "type_spec": "tf.SparseTensorSpec", "serialized": [{"class_name": "TensorShape", "items": [5002, 5002]}, "float32"]}]}], {}]}, "save_spec": {"class_name": "__tuple__", "items": [{"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [5002, 39522]}, "float32", "input_1"]}, {"class_name": "TypeSpec", "type_spec": "tf.SparseTensorSpec", "serialized": [{"class_name": "TensorShape", "items": [5002, 5002]}, "float32"]}]}, "keras_version": "2.7.0", "backend": "tensorflow", "model_config": {"class_name": "GCN", "config": {"n_labels": 2, "channels": 16, "activation": "relu", "output_activation": "softmax", "use_bias": false, "dropout_rate": 0.5, "l2_reg": 0.00025, "n_input_channels": 39522}}, "training_config": {"loss": {"class_name": "BinaryCrossentropy", "config": {"reduction": "sum", "name": "binary_crossentropy", "from_logits": false, "label_smoothing": 0.0, "axis": -1}, "shared_object_id": 1}, "metrics": [[{"class_name": "BinaryAccuracy", "config": {"name": "binary_accuracy", "dtype": "float32", "threshold": 0.5}, "shared_object_id": 2}, {"class_name": "Precision", "config": {"name": "precision", "dtype": "float32", "thresholds": null, "top_k": null, "class_id": null}, "shared_object_id": 3}, {"class_name": "Recall", "config": {"name": "recall", "dtype": "float32", "thresholds": null, "top_k": null, "class_id": null}, "shared_object_id": 4}, {"class_name": "AUC", "config": {"name": "auc", "dtype": "float32", "num_thresholds": 200, "curve": "ROC", "summation_method": "interpolation", "multi_label": false, "label_weights": null}, "shared_object_id": 5}]], "weighted_metrics": [[{"class_name": "BinaryAccuracy", "config": {"name": "weighted_binary_accuracy", "dtype": "float32", "threshold": 0.5}, "shared_object_id": 6}]], "loss_weights": null, "optimizer_config": {"class_name": "Adam", "config": {"name": "Adam", "learning_rate": 0.0010000000474974513, "decay": 0.0, "beta_1": 0.8999999761581421, "beta_2": 0.9990000128746033, "epsilon": 1e-07, "amsgrad": false}}}}2
õroot._d0"_tf_keras_layer*Ï{"name": "dropout", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout", "trainable": true, "dtype": "float32", "rate": 0.5, "noise_shape": null, "seed": null}, "shared_object_id": 7}2
ý
root._gcn0"_tf_keras_layer*Õ{"name": "gcn_conv", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "GCNConv", "config": {"name": "gcn_conv", "trainable": true, "dtype": "float32", "activation": "relu", "use_bias": false, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}, "shared_object_id": 8}, "bias_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 9}, "kernel_regularizer": {"class_name": "L2", "config": {"l2": 0.0002500000118743628}, "shared_object_id": 10}, "bias_regularizer": null, "kernel_constraint": null, "bias_constraint": null, "channels": 16}, "shared_object_id": 11, "build_input_shape": [{"class_name": "TensorShape", "items": [5002, 39522]}, {"class_name": "TensorShape", "items": [5002, 5002]}]}2
úroot._d1"_tf_keras_layer*Ô{"name": "dropout_1", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_1", "trainable": true, "dtype": "float32", "rate": 0.5, "noise_shape": null, "seed": null}, "shared_object_id": 12}2
±
root._gcn1"_tf_keras_layer*‰{"name": "gcn_conv_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "GCNConv", "config": {"name": "gcn_conv_1", "trainable": true, "dtype": "float32", "activation": "softmax", "use_bias": false, "kernel_initializer": {"class_name": "GlorotUniform", "config": {"seed": null}, "shared_object_id": 13}, "bias_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 14}, "kernel_regularizer": null, "bias_regularizer": null, "kernel_constraint": null, "bias_constraint": null, "channels": 2}, "shared_object_id": 15, "build_input_shape": [{"class_name": "TensorShape", "items": [5002, 16]}, {"class_name": "TensorShape", "items": [5002, 5002]}]}2
¹=root.keras_api.metrics.0"_tf_keras_metric*‚{"class_name": "Mean", "name": "loss", "dtype": "float32", "config": {"name": "loss", "dtype": "float32"}, "shared_object_id": 16}2
ê>root.keras_api.metrics.1"_tf_keras_metric*³{"class_name": "BinaryAccuracy", "name": "binary_accuracy", "dtype": "float32", "config": {"name": "binary_accuracy", "dtype": "float32", "threshold": 0.5}, "shared_object_id": 2}2
ü?root.keras_api.metrics.2"_tf_keras_metric*Å{"class_name": "Precision", "name": "precision", "dtype": "float32", "config": {"name": "precision", "dtype": "float32", "thresholds": null, "top_k": null, "class_id": null}, "shared_object_id": 3}2
ó@root.keras_api.metrics.3"_tf_keras_metric*¼{"class_name": "Recall", "name": "recall", "dtype": "float32", "config": {"name": "recall", "dtype": "float32", "thresholds": null, "top_k": null, "class_id": null}, "shared_object_id": 4}2
®Aroot.keras_api.metrics.4"_tf_keras_metric*÷{"class_name": "AUC", "name": "auc", "dtype": "float32", "config": {"name": "auc", "dtype": "float32", "num_thresholds": 200, "curve": "ROC", "summation_method": "interpolation", "multi_label": false, "label_weights": null}, "shared_object_id": 5}2
üBroot.keras_api.metrics.5"_tf_keras_metric*Å{"class_name": "BinaryAccuracy", "name": "weighted_binary_accuracy", "dtype": "float32", "config": {"name": "weighted_binary_accuracy", "dtype": "float32", "threshold": 0.5}, "shared_object_id": 6}2